org.gradle.jvmargs=-Xmx3G
essential.defaults.loom=0

group=at.yedel
version=3.0.1
mod.name=Keyyyyyyyy
mod.id=keyyyyyyyy
mod.group=at.yedel
mod.description=Enables keyboard repeat events on versions before 1.13
modIcon=assets/keyyyyyyyy/keyyyyyyyy.png
license=LGPL-3.0-only
modrinthLogoLink=https://cdn.modrinth.com/data/cached_images/aa92b26fd7b3679026b323110a565514dd4bd3cc.png

minecraft.version=1.8.9
loom.platform=forge